import type { Metadata } from "next";
import { Inter, Single_Day } from "next/font/google";
import { SignerProvider } from "@/state/signer";
import { NavBar } from "./components/NavBar/NavBar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SignerProvider>
      <html lang="en">
        <body className={inter.className}>
          <NavBar />
          {children}
        </body>
      </html>
    </SignerProvider>
  );
}
